### ISSUE TITLE
Megameklab: Variable size ladders

### ISSUE THREAD

**Issue by CrusherBob** [MegaMek/megameklab#1008]
### Environment
Megameklab 0.49.5

### Description
Ladders (other equipment) are now tagged as variable sized systems.  But when making a combat vehicle, you can't change the size of them when you click on the size number once they are added to a vehicle.

**Comment by CrusherBob** [comment]
Hmm, newly added ladders on support vehicles have the same probelm.  But the ladders already present on support vehicles can have their sizes changed.

**Comment by HammerGS** [comment]
Please add the logs per the bug report template.

**Comment by CrusherBob** [comment]
deleted old log
started megamek lab
clicked on new combat vehicle
changed tech type to advanced
when to 'add other equipment', chose a ladder
clicked on the 'size' number on the left, no response

searched for "Saurer-Bucher Fire Engine TLF-LL6500" and loaded
clicking on ladder size worked
closed megameklab
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/7884621/megameklablog.txt)

**Comment by CrusherBob** [comment]
Looks like it's related to the default ladder size of 1 being below with 'normal' min ladder size (20m?)

**Comment by HammerGS** [comment]
From the log.
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:139)
	at megameklab.com.util.CriticalTableModel$SpinnerCellEditor.getTableCellEditorComponent(CriticalTableModel.java:365)
	at java.desktop/javax.swing.JTable.prepareEditor(JTable.java:5797)
	at java.desktop/javax.swing.JTable.editCellAt(JTable.java:3508)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1127)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1057)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
