### ISSUE TITLE
[0.49.8 Snapshot] Export/Print to PDF Results in Exception

### ISSUE THREAD

**Issue by StowGnar** [MegaMek/megameklab#1094]
### Environment
What version of MekLab does your issue apply to? 0.49.8 Snapshot from 4/21. Came with MekHQ bundle, ran as standalone program.
What operating system are you using?  Windows 10 Home
What java version are you using?  11.0.13

### Description
Describe the issue and provide screenshots ingame if able. (See ExceptionDialog.png in attached ZIP) In the snapshots for the current version of MML from the MekHQ release, I am unable to Export to PDF or Print and use the Microsoft Print to PDF. Upon finishing the dialog to begin printing, an error message indicating an exception appears and the requested PDF file appears as a 0kb placeholder which can't be opened.
And provide the steps you have taken to reproduce the issue. In my particular environment, all I have to do is open my custom Dragon from cache, and then attempt to Export to PDF or Microsoft Print to PDF in order for the exception to occur.

### Files
[MML_NoPDF.zip](https://github.com/MegaMek/megameklab/files/8551433/MML_NoPDF.zip)

**Comment by Windchild292** [comment]
```
15:43:43,920 ERROR [megameklab.printing.RecordSheetTask] {AWT-EventQueue-0}
megameklab.printing.RecordSheetTask.done(RecordSheetTask.java:112) - 
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/w3c/dom/svg/SVGDocument
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at megameklab.printing.RecordSheetTask.done(RecordSheetTask.java:108)
Caused by: java.lang.NoClassDefFoundError: org/w3c/dom/svg/SVGDocument
	at org.apache.batik.anim.dom.SVGDOMImplementation.createDocument(SVGDOMImplementation.java:140)
	at org.apache.batik.dom.util.SAXDocumentFactory.startElement(SAXDocumentFactory.java:641)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:731)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:453)
	at org.apache.batik.dom.util.SAXDocumentFactory.createDocument(SAXDocumentFactory.java:287)
	at megameklab.printing.PrintRecordSheet.loadSVG(PrintRecordSheet.java:241)
	at megameklab.printing.PrintRecordSheet.loadTemplate(PrintRecordSheet.java:280)
	at megameklab.printing.PrintRecordSheet.createDocument(PrintRecordSheet.java:287)
	at megameklab.printing.PrintRecordSheet.exportPDF(PrintRecordSheet.java:346)
	at megameklab.printing.RecordSheetTask$ExportTask.doInBackground(RecordSheetTask.java:194)
	at megameklab.printing.RecordSheetTask$ExportTask.doInBackground(RecordSheetTask.java:167)
```

**Comment by Windchild292** [comment]
I have no idea how MML could compile without that class being included... which is 'fun'

**Comment by Windchild292** [comment]
Resolved in https://github.com/MegaMek/mekhq/commit/e6a20dbf8bb0044832f424240d0a3fd9ff748499
