### ISSUE TITLE
1.53 : Bug with changing number of shots for BA SRM ammo

### ISSUE THREAD

**Issue by Question2** [MegaMek/megameklab#11]
If you select an elemental armor (MG) point, then right click the BA SRM ammo and change the number of shots, the tonnage indicator at the bottom does not change. It only changes if you un-allocate the SRM ammo first then change the number of shots.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/264949/megameklablog.txt)

**Comment by BLOODWOLF333** [comment]
I verified this, the Suit Weight only changes when you adjust the number shots while the SRM ammo is inside the Unallocated Equipment column.  Can set the SRM ammo to 1 shot and then allocate the ammo to the body, then change the ammo to 4 shots without MML adding any additional weight so, free shots.  Did not test if this actually makes it into MM like this without MM correcting it or throwing an error.

**Comment by arlith** [comment]
Turns out there was an exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.swing.JPanel cannot be cast to megameklab.com.ui.BattleArmor.tabs.BuildTab
	at megameklab.com.util.Mech.DropTargetCriticalList$12.actionPerformed(DropTargetCriticalList.java:344)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
```

There was code to refresh, however it was using `Component.getParent` and making assumptions about the parent, casing it to a `BuildView` and calling refresh.  There was a better way to do this, and I updated the code.
