### ISSUE TITLE
(0.49.8) Uncaught Java Exception

### ISSUE THREAD

**Issue by CampaignAnon** [MegaMek/megameklab#1165]
As per the pop up in MegaMekLab, I am reporting an uncaught java exception with a Battle Armor unit.
[Error material.zip](https://github.com/MegaMek/megameklab/files/9466414/Error.material.zip)

**Comment by Windchild292** [comment]
```
21:36:11,529 ERROR [megameklab.MegaMekLab] {AWT-EventQueue-0}
megameklab.MegaMekLab.lambda$main$0(MegaMekLab.java:39) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.templates.BattleArmorTROView.initModel(BattleArmorTROView.java:98)
	at megamek.common.templates.TROView.createView(TROView.java:87)
	at megamek.client.ui.panes.EntityViewPane.updateDisplayedEntity(EntityViewPane.java:93)
	at megamek.client.ui.swing.dialog.AbstractUnitSelectorDialog.refreshUnitView(AbstractUnitSelectorDialog.java:569)
	at megamek.client.ui.swing.dialog.AbstractUnitSelectorDialog.lambda$initComponents$0(AbstractUnitSelectorDialog.java:196)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:186)
	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:723)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:972)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1185)
```

**Comment by Windchild292** [comment]
NPE experienced at `setModelData("armorType", armor.getName().replaceAll("^BA\\s+", ""));`

**Comment by HammerGS** [comment]
Starting MegaMekLab v0.49.8
	Build Date: 2022-05-27T13:20:51.792144500
	Release Date: 2022-02-18
	Today: 2022-08-31
	Origin Project: MegaMekLab
	Java Vendor: Oracle Corporation
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMekLab: 1 GB

**Comment by neoancient** [comment]
I can't reproduce this. I assume it is occurring with the included BA file. Does it happen when loading the unit or when modifying?

**Comment by HammerGS** [comment]
I'm able to duplicate it with MML running from the Repo.
![image](https://user-images.githubusercontent.com/13752452/188495743-416c781e-5a50-409b-94a9-8af7f7f33d7a.png)

I added the file to data directory, started MML, used the load existing unit. It starts to load and then the error in the screen shot appears. My error log for reference.

**Comment by HammerGS** [comment]
@CampaignAnon What version of MegaMekLab was the file made on?

**Comment by CampaignAnon** [comment]
> @CampaignAnon What version of MegaMekLab was the file made on?

The earliest version of megameklab I still have with it in the customs folder is 43.1, so probably that or 43.0

**Comment by HammerGS** [comment]
> > @CampaignAnon What version of MegaMekLab was the file made on?
> 
> The earliest version of megameklab I still have with it in the customs folder is 43.1, so probably that or 43.0

That's likely the issue. While we try to make sure stuff is backwards compatible those files are back to 2017 and there has been just too much code changed since then. Anything from that era would likely need to be remade.
