### ISSUE TITLE
Uncaught java exception? Attached all logs and unit file as the program requested.

### ISSUE THREAD

**Issue by xenoscepter** [MegaMek/megameklab#1242]
Basically the title. Unsure what went wrong, or why, or if this is even a useful issue report, just... following directions. FWIW, the program went back to running after I saved the unit.
[logs_unitfile.zip](https://github.com/MegaMek/megameklab/files/11165788/logs_unitfile.zip)

**Comment by HammerGS** [comment]
From the log 

```
22:35:31,703 ERROR [megameklab.MegaMekLab] {AWT-EventQueue-0}
megameklab.MegaMekLab.lambda$main$0(MegaMekLab.java:39) - Uncaught Exception Detected
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:139)
	at java.desktop/javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:161)
	at megameklab.ui.generalUnit.TransportTab$SpinnerCellEditor.getTableCellEditorComponent(TransportTab.java:854)
	at java.desktop/javax.swing.JTable.prepareEditor(JTable.java:5812)
	at java.desktop/javax.swing.JTable.editCellAt(JTable.java:3508)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleasedDND(BasicTableUI.java:1208)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1175)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
```
