### ISSUE TITLE
Industrial battlemech armor causes NullPointerException

### ISSUE THREAD

**Issue by FixDis** [MegaMek/megameklab#1440]
### Environment
MegaMekLab v0.49.18
Windows 11
Eclipse Adoptium Java Version: 11.0.21

### Description
Putting Industrial armor on a tournament-legal battlemech causes a NullPointerException

**Comment by HammerGS** [comment]
We need logs.

**Comment by FixDis** [comment]
[megameklab.log](https://github.com/MegaMek/megameklab/files/14397078/megameklab.log)
?

**Comment by HammerGS** [comment]
```
00:24:55,512 ERROR [megameklab.MegaMekLab] {AWT-EventQueue-0}
megameklab.MegaMekLab.lambda$main$0(MegaMekLab.java:40) - Uncaught Exception Detected
java.lang.NullPointerException
	at megameklab.ui.mek.BMStructureTab.createArmorMountsAndSetArmorType(BMStructureTab.java:507)
	at megameklab.ui.mek.BMStructureTab.armorTypeChanged(BMStructureTab.java:971)
	at megameklab.ui.generalUnit.MVFArmorView.lambda$actionPerformed$2(MVFArmorView.java:351)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at megameklab.ui.generalUnit.MVFArmorView.actionPerformed(MVFArmorView.java:351)
```
