### ISSUE TITLE
Export to PDF Broken on Warships.

### ISSUE THREAD

**Issue by JoeJohnJordan** [MegaMek/megameklab#1635]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Trying to export a Warship Record Sheet to PDF results in a null point exception and if you attempt to print any warship record sheet after the fact it results in a a null point exception and gives you a corrupted PDF file that is unable to be opened necessitating Mega Mek Lab to be reopened to print a sheet succesfully.

Attempting to print without exporting prior results in the normal function of the process.

### Operating System *

Windows 10

### Java Version *

11.0.17

### MegaMek Suite Version *

v0.49.19.1

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
Can you post the log file? I think this might be the issue that was addressed in https://github.com/MegaMek/megameklab/pull/1601 .

**Comment by JoeJohnJordan** [comment]
![image](https://github.com/user-attachments/assets/92579803-09d9-4ec4-92d8-4b93fb46704a) I forgot about that previous one, I saw it and I guess I missed it when checking around the other day for same issues.

**Comment by JoeJohnJordan** [comment]
[megamek.log](https://github.com/user-attachments/files/17380566/megamek.log) Totally missed and forgot about that prior issue, I did notice it last month when browsing but didn't remember/notice it again when I posted this issue.

**Comment by JoeJohnJordan** [comment]
[megameklab.log](https://github.com/user-attachments/files/17380585/megameklab.log)
Totally missed and forgot about that prior issue, I did notice it last month when browsing but didn't remember/notice it again when I posted this issue.

**Comment by HammerGS** [comment]
The logs are empty.

**Comment by SJuliez** [comment]
Printing the Enterprise Super Carrier results in this exception (but a functional PDF), possibly because the RS is two-sided. One-sided WS like the Nightwing causes no errors.

```

15:38:36,858 ERROR [megameklab.printing.RecordSheetTask] {AWT-EventQueue-0}
megameklab.printing.RecordSheetTask.done(RecordSheetTask.java:131) - 
java.util.concurrent.ExecutionException: java.awt.print.PrinterException: Error getting page or printable.[ java.lang.NullPointerException: Cannot invoke "megameklab.printing.PrintRecordSheet.getFirstPage()" because "rs" is null ]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at megameklab.printing.RecordSheetTask.done(RecordSheetTask.java:127)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:318)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.awt.print.PrinterException: Error getting page or printable.[ java.lang.NullPointerException: Cannot invoke "megameklab.printing.PrintRecordSheet.getFirstPage()" because "rs" is null ]
	at java.desktop/sun.print.RasterPrinterJob.printPage(RasterPrinterJob.java:2147)
	at java.desktop/sun.print.RasterPrinterJob.print(RasterPrinterJob.java:1661)
	at megameklab.printing.RecordSheetTask$PrintTask.doInBackground(RecordSheetTask.java:179)
	at megameklab.printing.RecordSheetTask$PrintTask.doInBackground(RecordSheetTask.java:156)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "megameklab.printing.PrintRecordSheet.getFirstPage()" because "rs" is null
	at megameklab.printing.RecordSheetTask$RSBook.getPrintable(RecordSheetTask.java:270)
	at java.desktop/sun.print.RasterPrinterJob.printPage(RasterPrinterJob.java:2145)
	... 10 more


```

**Comment by exeea** [comment]
The issue seems have been fixed already.
