### ISSUE TITLE
Error in the nightly

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megameklab#1670]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

```
13:49:33,156 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.02-SNAPSHOT
    Build Date: 2024-12-29T03:24:36.926837817
    Today: 2024-12-29
    Origin Project: MegaMekLab
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 1 GB
    MM Code Revision: Unknown
    MML Code Revision: b9c99e9e97b79b60671ac87ff6d849caec30cb6a
    MHQ Code Revision: Unknown


13:49:33,158 INFO  [megameklab.MegaMekLab] {main}
megameklab.MegaMekLab.initializeLogging(MegaMekLab.java:82) - Starting MegaMekLab v0.50.02-SNAPSHOT
    Build Date: 2024-12-29T03:24:36.926837817
    Today: 2024-12-29
    Origin Project: MegaMekLab
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_US
    Total memory available to MegaMekLab: 1 GB
    MM Code Revision: Unknown
    MML Code Revision: b9c99e9e97b79b60671ac87ff6d849caec30cb6a
    MHQ Code Revision: Unknown


13:49:33,159 INFO  [megamek.client.ui.swing.util.FontHandler] {main}
megamek.client.ui.swing.util.FontHandler.initializeFonts(FontHandler.java:114) - Loading fonts from data/fonts/

13:49:33,401 INFO  [megamek.client.ui.swing.util.FontHandler] {main}
megamek.client.ui.swing.util.FontHandler.initializeFonts(FontHandler.java:123) - Loading fonts from Java's GraphicsEnvironment

13:49:33,750 INFO  [megamek.client.ui.preferences.SuitePreferences] {main}
megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:125) - Loading user preferences from: mmconf/mm.preferences

13:49:33,754 ERROR [megamek.client.ui.preferences.SuitePreferences] {main}
megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:151) - loadFromFile - Ignored
java.io.FileNotFoundException: mmconf\mm.preferences (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:128)
	at megameklab.MegaMekLab.startup(MegaMekLab.java:99)
	at megameklab.MegaMekLab.main(MegaMekLab.java:78)

13:49:33,755 INFO  [megamek.client.ui.preferences.SuitePreferences] {main}
megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:125) - Loading user preferences from: mmconf/mml.preferences

13:49:33,755 ERROR [megamek.client.ui.preferences.SuitePreferences] {main}
megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:151) - loadFromFile - Ignored
java.io.FileNotFoundException: mmconf\mml.preferences (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at megamek.client.ui.preferences.SuitePreferences.loadFromFile(SuitePreferences.java:128)
	at megameklab.MegaMekLab.startup(MegaMekLab.java:100)
	at megameklab.MegaMekLab.main(MegaMekLab.java:78)

13:49:33,784 INFO  [megamek.common.MMRandom] {Mek Cache Loader}
megamek.common.MMRandom.generate(MMRandom.java:42) - Generating RNG type #1

13:49:33,798 WARN  [megamek.common.WeaponOrderHandler] {Mek Cache Loader}
megamek.common.WeaponOrderHandler.loadWeaponOrderFile(WeaponOrderHandler.java:171) - Could not load custom weapon orders from customWeaponOrder.xml
```

another error once you open the unit selector
```
13:43:42,148 ERROR [megamek.common.loaders.MtfFile] {Mek Cache Loader}
megamek.common.loaders.MtfFile.getEntity(MtfFile.java:532) - 
java.lang.NullPointerException: Cannot invoke "String.trim()" because "this.model" is null
	at megamek.common.loaders.MtfFile.getEntity(MtfFile.java:264)
	at megamek.common.MekFileParser.parse(MekFileParser.java:213)
	at megamek.common.MekFileParser.<init>(MekFileParser.java:69)
	at megamek.common.MekFileParser.<init>(MekFileParser.java:62)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:791)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:776)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:776)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:776)
	at megamek.common.MekSummaryCache.checkForChanges(MekSummaryCache.java:254)
	at megamek.common.MekSummaryCache.loadMekData(MekSummaryCache.java:243)
	at megamek.common.MekSummaryCache.lambda$getInstance$0(MekSummaryCache.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)

13:43:42,148 ERROR [megamek.common.MekFileParser] {Mek Cache Loader}
megamek.common.MekFileParser.<init>(MekFileParser.java:71) - 
java.lang.Exception: java.lang.NullPointerException: Cannot invoke "String.trim()" because "this.model" is null
	at megamek.common.loaders.MtfFile.getEntity(MtfFile.java:533)
	at megamek.common.MekFileParser.parse(MekFileParser.java:213)
	at megamek.common.MekFileParser.<init>(MekFileParser.java:69)
	at megamek.common.MekFileParser.<init>(MekFileParser.java:62)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:791)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:776)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:776)
	at megamek.common.MekSummaryCache.loadMeksFromDirectory(MekSummaryCache.java:776)
	at megamek.common.MekSummaryCache.checkForChanges(MekSummaryCache.java:254)
	at megamek.common.MekSummaryCache.loadMekData(MekSummaryCache.java:243)
	at megamek.common.MekSummaryCache.lambda$getInstance$0(MekSummaryCache.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.trim()" because "this.model" is null
	at megamek.common.loaders.MtfFile.getEntity(MtfFile.java:264)
```

### Steps to Reproduce

1.  just launch megameklab

### Operating System *

Windows 11

### Java Version *

17

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMekLab Version

nightly

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by pavelbraginskiy** [comment]
Does MML function normally after getting these errors? The first time MML is launched, it is expected that your preferences and the unit cache will fail to load, but then they should be built up and normal operation should resume.

**Comment by rjhancock** [comment]
The first errors can be ignored as the app is just trying to load a file that doesn't exist and re-builds as it needs. The second set of logs is the actual error that might need to be addressed.
