### ISSUE TITLE
MegaMekLab doesn't seem to work with JRE 10 ?

### ISSUE THREAD

**Issue by pmjdebruijn** [MegaMek/megameklab#187]
~/Downloads/megameklab-0.45.0$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)

~/Downloads/megameklab-0.45.0$ java -Xmx512m -jar MegaMekLab.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at megamek.MegaMek.<clinit>(MegaMek.java:80)
	at megameklab.com.MegaMekLab.setupLogging(MegaMekLab.java:169)
	at megameklab.com.MegaMekLab.main(MegaMekLab.java:74)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 3 more

**Comment by pmjdebruijn** [comment]
With this JRE it works just fine again:

~/Downloads/megameklab-0.45.0$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by neoancient** [comment]
https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds

**Comment by wildj79** [comment]
doh, @neoancient beat me to it
