### ISSUE TITLE
Cockpit unavailable at certain years

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#278]
This is going to be tricky to duplicate.  Running 45.4 via Eclipse.  I've had this error a couple of times but never been able to track the specific steps down to duplicate it.

If occurs when I've built a unit and used the reset Chassis to start a new unit.  I'll change the Chassis and Model names and then the date.  When the error happens the cockpit dropdown changes to -error-, and then you can change the walk MP but the run MP won't update.

From the Log:
```
Error loading XML for entity verifier: data\mechfiles\UnitVerifierOptions.xml (The system cannot find the path specified)
java.io.FileNotFoundException: data\mechfiles\UnitVerifierOptions.xml (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at megamek.common.verifier.EntityVerifier.getInstance(EntityVerifier.java:104)
	at megamek.common.templates.TROView.<init>(TROView.java:76)
	at megamek.common.templates.MechTROView.<init>(MechTROView.java:42)
	at megamek.common.templates.TROView.createView(TROView.java:86)
	at megameklab.com.ui.tabs.PreviewTab.refresh(PreviewTab.java:66)
	at megameklab.com.ui.Mek.MainUI.refreshPreview(MainUI.java:247)
	at megameklab.com.ui.Mek.tabs.StructureTab.modelChanged(StructureTab.java:584)
	at megameklab.com.ui.view.BasicInfoView.lambda$2(BasicInfoView.java:423)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at megameklab.com.ui.view.BasicInfoView.focusLost(BasicInfoView.java:423)

```

```
java.lang.ArrayIndexOutOfBoundsException: 8
	at megamek.common.Entity.getOArmor(Entity.java:3028)
	at megamek.common.Mech.getOArmor(Mech.java:1982)
	at megamek.common.Entity.getOArmor(Entity.java:3010)
	at megamek.common.templates.MechTROView.lambda$addArmorAndStructure$3(MechTROView.java:157)
	at megamek.common.templates.TROView.lambda$addArmorStructureEntries$4(TROView.java:358)
```
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megameklab.com.ui.view.MekChassisView.getCockpitType(MekChassisView.java:736)
	at megameklab.com.ui.view.MekChassisView.refreshFullHeadEject(MekChassisView.java:579)
	at megameklab.com.ui.view.MekChassisView.refresh(MekChassisView.java:394)
	at megameklab.com.ui.view.MekChassisView.actionPerformed(MekChassisView.java:781)
	at javax.swing.JComboBox.fireActionEvent(Unknown Source)
	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at megameklab.com.ui.view.MekChassisView.refreshEnhancement(MekChassisView.java:573)
	at megameklab.com.ui.view.MekChassisView.refresh(MekChassisView.java:393)
	at megameklab.com.ui.Mek.tabs.StructureTab.updateTechLevel(StructureTab.java:651)
	at megameklab.com.ui.Mek.tabs.StructureTab.yearChanged(StructureTab.java:590)
	at megameklab.com.ui.view.BasicInfoView.lambda$3(BasicInfoView.java:427)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at megameklab.com.ui.view.BasicInfoView.focusLost(BasicInfoView.java:427)
```
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/3000559/megameklablog.txt)

**Comment by neoancient** [comment]
Closing as non-reproducible.

**Comment by assaultdoor** [comment]
I was able to reproduce this with 0.47.6. If the introduction year is set to before 2463, I get the same results: -error- cockpit type and changing walking speed doesn't change running speed. I can also change armor tonnage without the number of armor points updating.

This isn't restricted to new units after resetting the chassis. I could make it happen immediately after loading MML and picking "New Mek", or after loading a valid unit.

This can result if I'm building a unit in MML that I've already created by hand. If I've typed "305" into the year and switch windows to my notes to see whether I had 3054 or 3055, the year becomes 305 and I get to start building the unit over again.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/4662758/megameklablog.txt)

**Comment by pavelbraginskiy** [comment]
The Year box should be limited to a minimum value, before which you should construct a Primitive BattleMech instead.
Although, I'm not too sure what that year should be, as the standard BattleMech predates the standard cockpit by a few years: https://bg.battletech.com/forums/index.php?topic=87134.0
