### ISSUE TITLE
Can't print Masakari MC-J in either 0.1.59 or 0.41.24

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megameklab#35]
The following NPE is reported the megameklab log:

java.lang.NullPointerException
        at megameklab.com.ui.Mek.Printing.PrintMech.printImage(PrintMech.java:182)
        at megameklab.com.ui.Mek.Printing.PrintMech.print(PrintMech.java:93)
        at sun.print.RasterPrinterJob.printPage(RasterPrinterJob.java:2106)
        at sun.print.RasterPrinterJob.print(RasterPrinterJob.java:1488)
        at megameklab.com.ui.Mek.Printing.PrintMech.print(PrintMech.java:612)
        at megameklab.com.util.UnitPrintManager.printAllUnits(UnitPrintManager.java:223)
        at megameklab.com.util.UnitPrintManager.printEntity(UnitPrintManager.java:87)
        at megameklab.com.util.MenuBarCreator.jMenuPrintCurrentUnit(MenuBarCreator.java:1019)
        at megameklab.com.util.MenuBarCreator.access$1600(MenuBarCreator.java:66)
        at megameklab.com.util.MenuBarCreator$27.actionPerformed(MenuBarCreator.java:428)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)

I should add that I'm running MML on Fedora 24, if that matters.  I have been able to print units before.

**Comment by HammerGS** [comment]
Checking on a Windows machine I'm able to get things to print.  Might be something OS specific but someone like @Dylan-M @arlith would need to double check.  To help out I've attached the RS for you so you have it.

[Masakari.pdf](https://github.com/MegaMek/megameklab/files/517779/Masakari.pdf)

**Comment by mhjacks** [comment]
I believe what we're dealing with is a straightforward case mismatch, which will work fine on Windows but will fail on Linux (and maybe MacOS?):

 Looking at the code, we have:

```
           if (mech.getArmor(Mech.LOC_LLEG) > 0) {
                ImageHelper.loadSVGImage(new File("data/images/recordsheets/Armor_LLEG_"+mech.getArmor(Mech.LOC_LLEG)+"_Humanoid.svg")).render(g2d);
            }

```
Looking in the correponding directory we have:
```
-rw-r--r-- 1 mjackson mjackson 36452 Oct 15 10:01 Armor_LLeg_10_Humanoid.svg
-rw-r--r-- 1 mjackson mjackson 36980 Oct 15 10:01 Armor_LLeg_11_Humanoid.svg
-rw-r--r-- 1 mjackson mjackson 37482 Oct 15 10:01 Armor_LLeg_12_Humanoid.svg
-rw-r--r-- 1 mjackson mjackson 37985 Oct 15 10:01 Armor_LLeg_13_Humanoid.svg
-rw-r--r-- 1 mjackson mjackson 38467 Oct 15 10:01 Armor_LLeg_14_Humanoid.svg

```

I see the same potential issue with RLeg files and possibly others.

**Comment by mhjacks** [comment]
From grepping the source, it looks like this is the only place these things are referenced.  I see two failrly obvious approaches to a fix here:

1.  Change the code to reference the filename as it appears on Linux (which will work on Mac and Windows too).
2.  Change the filenames to match what the code expects to find

Which would you prefer?  I am happy to fork and propose a patch to fix this; what sort of patch would you prefer?

**Comment by Dylan-M** [comment]
A pull request is fine, I assume it's the filename that needs to change if other filenames are all caps that way. If that isn't the case, then change the code instead.

**Comment by mhjacks** [comment]
Very well.  The filenames in the git repo are all mixed case.  I will work on a PR to change the code.  Thanks!
