### ISSUE TITLE
MML Doesn't load a second file

### ISSUE THREAD

**Issue by Notsonoble** [MegaMek/megameklab#355]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MML 0.47.0 Standalone
Java 11.04
Ubuntu 18.04 64-bit

### Description
If I open MML and load a unit either from cache or a file, and then load another one, nothing happens. This doesn't seem to matter if I edit or not.

Sometimes I can try and load a second time and it works, sometimes MML becomes unresponsive.

Had this in .46, tried .47 dev to see if it changed before providing ticket.
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/3735600/megameklablog.txt)

### Files
Provide the megameklablog.txt file for any NPE's or errors that MekLab might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklablog.txt file
And provide the unit's file that the issue relates to if this is a unit-specific bug.
(Delete the above lines)

**Comment by HammerGS** [comment]
From the Log.
```
Starting MegaMekLab version: 0.47.0
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class megamek.common.AmmoType cannot be cast to class megamek.common.WeaponType (megamek.common.AmmoType and megamek.common.WeaponType are in unnamed module of loader 'app')
	at megameklab.com.ui.util.BayWeaponCriticalTree$BayNode.getTooltip(BayWeaponCriticalTree.java:673)
	at megameklab.com.ui.util.BayWeaponCriticalTree$1.getTreeCellRendererComponent(BayWeaponCriticalTree.java:726)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3155)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.updateNodeSizes(VariableHeightLayoutCache.java:903)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.invalidateSizes(VariableHeightLayoutCache.java:371)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3850)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8728)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1176)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1183)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1168)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1183)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1168)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1183)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1168)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1183)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1168)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1183)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1168)
	at java.desktop/java.awt.Container.updateChildGraphicsData(Container.java:1183)
	at java.desktop/java.awt.Component.updateGraphicsData(Component.java:1168)
	at java.desktop/java.awt.Component.setGraphicsConfiguration(Component.java:1156)
	at java.desktop/java.awt.Container.removeAll(Container.java:1328)
	at megameklab.com.ui.aerospace.DropshipMainUI.reloadTabs(DropshipMainUI.java:179)
	at megameklab.com.util.MenuBarCreator.reload(MenuBarCreator.java:1385)
	at megameklab.com.util.MenuBarCreator.loadUnit(MenuBarCreator.java:1263)
	at megameklab.com.util.MenuBarCreator.jMenuLoadEntity_actionPerformed(MenuBarCreator.java:1004)
	at megameklab.com.util.MenuBarCreator.lambda$loadFileMenuOptions$31(MenuBarCreator.java:372)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by neoancient** [comment]
Please provide the steps to reproduce this. Specifically, which unit(s) are you working with? I can't recreate the problem.

**Comment by Notsonoble** [comment]
I was opening the Leopard dropship, then anything else.

**Comment by neoancient** [comment]
Closing as stale due to inability to reproduce with information provided.
