### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#379]
The log below was posted on Discord. Still trying to get more details but don't want to lose this.
### Environment
What version of MekLab does your issue apply to?  0.46.0
What operating system are you using? Windows 10
What java version are you using?  Uncertain

### Description
```
log4j:WARN Could not find [log4j.dtd] using [sun.misc.Launcher$AppClassLoader@647e05] class loader, parsed without DTD.
log4j:WARN Continuable parsing error 4 and column 69
log4j:WARN Element type "log4j:configuration" must be declared.
log4j:WARN Continuable parsing error 7 and column 72
log4j:WARN Element type "appender" must be declared.
log4j:WARN Continuable parsing error 8 and column 57
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 9 and column 44
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 10 and column 49
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 11 and column 49
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 12 and column 56
log4j:WARN Element type "layout" must be declared.
log4j:WARN Continuable parsing error 14 and column 93
log4j:WARN Element type "param" must be declared.
log4j:WARN Continuable parsing error 39 and column 11
log4j:WARN Element type "root" must be declared.
log4j:WARN Continuable parsing error 40 and column 30
log4j:WARN Element type "level" must be declared.
log4j:WARN Continuable parsing error 41 and column 35
log4j:WARN Element type "appender-ref" must be declared.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at megamek.common.Entity.<clinit>(Entity.java:167)
	at megamek.common.MiscType.createISBAAdvancedArmor(MiscType.java:3364)
	at megamek.common.MiscType.initializeTypes(MiscType.java:1680)
	at megamek.common.EquipmentType.initializeTypes(EquipmentType.java:645)
	at megameklab.com.ui.MegaMekLabMainUI.<init>(MegaMekLabMainUI.java:50)
	at megameklab.com.ui.Mek.MainUI.<init>(MainUI.java:73)
	at megameklab.com.ui.Mek.MainUI.<init>(MainUI.java:69)
	at megameklab.com.MegaMekLab.main(MegaMekLab.java:157)
Caused by: java.util.MissingResourceException: Can't find bundle for base name megamek.common.messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
	at java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.util.ResourceBundle.getBundle(Unknown Source)
	at megamek.common.Messages.<clinit>(Messages.java:29)
	... 8 more
Caused by: java.lang.NullPointerException
	at megamek.common.util.EncodeControl.newBundle(EncodeControl.java:55)
	at java.util.ResourceBundle.loadBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)

```

**Comment by neoancient** [comment]
Without more information there's not much I can do with this. It looks like an incomplete install or user manipulation of the jar.
