### ISSUE TITLE
Array out of Bounds Exception when printing Warship

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#57]
Tried to test print a warship.  Getting a ArrayIndexOutOfBoundsException: 6

Using the Print-Other Unit-Aegis Heavy Cruiser (2582)

Get the following error:

```
java.lang.ArrayIndexOutOfBoundsException: 6
	at megameklab.com.util.ImageHelperAero.getLocationAbbrs(ImageHelperAero.java:45)
	at megameklab.com.util.ImageHelperAero.printAeroWeaponsNEquipment(ImageHelperAero.java:236)
	at megameklab.com.ui.Aero.Printing.PrintAero.printWeaponsNEquipment(PrintAero.java:284)
	at megameklab.com.ui.Aero.Printing.PrintAero.printImage(PrintAero.java:84)
	at megameklab.com.ui.Aero.Printing.PrintAero.print(PrintAero.java:68)
	at sun.print.RasterPrinterJob.printPage(Unknown Source)
	at sun.print.RasterPrinterJob.print(Unknown Source)
	at megameklab.com.ui.Aero.Printing.PrintAero.print(PrintAero.java:309)
	at megameklab.com.util.UnitPrintManager.printAllUnits(UnitPrintManager.java:270)
	at megameklab.com.util.UnitPrintManager.printEntity(UnitPrintManager.java:89)
	at megameklab.com.util.UnitPrintManager.printSelectedUnit(UnitPrintManager.java:415)
	at megameklab.com.util.UnitPrintManager$2.actionPerformed(UnitPrintManager.java:359)
	```

**Comment by wildj79** [comment]
Looks like `ImageHelperAero.java` is designed to be used with Aerospace fighters specifically.  `LOCATION_ABBRS` only has 6 indices, but an `Entity` of type `Warship` is being passed in, which has 8 locations.  There either needs to be a new `ImageHelper` class created for warships, or the `ImageHelper` classes need to be refactored to be more generic.
