### ISSUE TITLE
Some Gallowglass Variants fail to showup if loaded through the Cache. After that mml is unresponsive

### ISSUE THREAD

**Issue by BRDiger** [MegaMek/megameklab#62]
![gallowglass](https://cloud.githubusercontent.com/assets/18350902/25178956/2d31540a-2508-11e7-8f39-5324fe6484c8.PNG)
Version was a freshly extracted Daily 0.43-2 (376) without my own customs though i first stumbled upon this problem in Daily 367. Only thing i did was starting mm for the Cache generation (mml seems to stop if it is supposed to do it).
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/934124/megameklablog.txt)
[megameklog.txt](https://github.com/MegaMek/megameklab/files/934125/megameklog.txt)

**Comment by HammerGS** [comment]
You need to CTRL- Select in the Type box to get all the tech levels. Then the 7 Gallowglas will show.  Using the most current versions in the Repo I can't duplicate the unresponsiveness.


![image](https://cloud.githubusercontent.com/assets/13752452/25190565/d49e8952-24e9-11e7-83cd-2b4d4b5cb2c9.png)

**Comment by BRDiger** [comment]
Thats not fixing the problem for me...the problem is that he program can´t read the mechfile from cache as it seems. Look again at the picture I actually clicked the 4glsa...it still showed the 2gls

**Comment by HammerGS** [comment]
What link did you download the daily from?

**Comment by BRDiger** [comment]
Sure, it´s one of akjosch´s: http://shiva.baka-sama.de:8080/job/MekHQ/376/artifact/MekHQ/mekhq-DAILY-windows.zip

**Comment by Dylan-M** [comment]
So, I'm inclined to close this bug for one simple reason:
Daily builds from git are known to be likely unstable and are not supported.

I will however leave that decision to @HammerGS since he's been the one running point on this. I do feel however, that if he has built from source and cannot replicate, that it should be closed as an issue with the builds from git by that Jenkins server.

**Comment by BRDiger** [comment]
Fine by me, if it´s not a real bug all the better. I would have posted it on the old forums to ask directly if it was a bug, but that seems to be down.

**Comment by HammerGS** [comment]
Ok, downloading and running MML generates this error. Which 

```
Exception in thread "Mech Cache Loader" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/converters/Converter
	at megamek.common.EquipmentType.getGameOptions(EquipmentType.java:1030)
	at megamek.common.weapons.ACWeapon.getDamage(ACWeapon.java:109)
	at megamek.common.Entity.hasViableWeapons(Entity.java:835)
	at megamek.common.Entity.initMilitary(Entity.java:823)
	at megamek.common.MechFileParser.postLoadInit(MechFileParser.java:896)
	at megamek.common.MechFileParser.parse(MechFileParser.java:206)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:119)
	at megamek.common.MechSummaryCache.loadMechsFromZipFile(MechSummaryCache.java:654)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:554)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:246)
	at megamek.common.MechSummaryCache$1.run(MechSummaryCache.java:95)
```

Given this is coming from @Akjosch Jenkins I'm not sure anything can be done. I would avoid using Daily builds in general.  

re: Forums - they have moved to https://www.megamek.org/bb/index.php

Closing this.
