### ISSUE TITLE
Array Index Error when changing Squad Size

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#72]
Need to create a WoB version of the Nighthawk Mk XXI armor, if I load the current version in MML, it loads with 4, as soon as I change the squad size to 6 it throughs an ArrayIndexOutofBoundsException

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 5
	at megamek.common.Entity.initializeInternal(Entity.java:2858)
	at megamek.common.Infantry.initializeInternal(Infantry.java:629)
	at megamek.common.BattleArmor.autoSetInternal(BattleArmor.java:757)
	at megameklab.com.ui.BattleArmor.tabs.StructureTab.stateChanged(StructureTab.java:1230)

**Comment by neoancient** [comment]
See #77 
Fixed in 9ede598
