### ISSUE TITLE
ClassCastException: class megamek.common.AmmoType cannot be cast to class megamek.common.WeaponType

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#755]
Steps to Recreate.

1) Start MML
2) Load Existing Unit
3) Load Union (2708)
4) Change to Transport Tab
5) Use load from Cache
6) Select Excalibur (2786)

The program will partially freeze and need to be restarted to regain full functionality again.

### Environment
What version of MekLab does your issue apply to?  47.10 SNAPSHOT
What operating system are you using?  Windows

### Files
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class megamek.common.AmmoType cannot be cast to class megamek.common.WeaponType (megamek.common.AmmoType and megamek.common.WeaponType are in unnamed module of loader 'app')
	at megameklab.com.ui.util.BayWeaponCriticalTree$BayNode.getTooltip(BayWeaponCriticalTree.java:689)
	at megameklab.com.ui.util.BayWeaponCriticalTree$1.getTreeCellRendererComponent(BayWeaponCriticalTree.java:777)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3155)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.updateNodeSizes(VariableHeightLayoutCache.java:903)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.invalidateSizes(VariableHeightLayoutCache.java:371)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3850)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
```

**Comment by neoancient** [comment]
I'm not able to reproduce this. I can't think of anything that might have affected it since it was posted, so I checked out the code in the state it was in when this was posted, and I still can't produce the error.

**Comment by HammerGS** [comment]
Just tested this again and can't duplicate it. Closing.
