### ISSUE TITLE
[043.4] [MegmekLab] [Windows] Exeption

### ISSUE THREAD

**Issue by BRDiger** [MegaMek/megameklab#92]
While updating my Custom units to the new Version via Megameklab i noticed that loading the old files always defaulted to tech base: clan while the units were of mixed nature. Setting them back to Mixed:IS sometimes resulted in the Amor Type: Drop-downmenue showing only clan tech. (And Ferror-Lamellor in 3084 only being available as Mixed-C not Mixed-IS) After switching back to mixed the Critical allocation screen sometimes wouldn´t update...
That behavour is true for the mmlab 43.4 single download as well as the mixed one for mmhq (see https://github.com/MegaMek/mekhq/issues/496) 
I added the log with the exeption as well as the Spider i was last working on (substituting the WERPPC to a normal Clan ERPPC )   Exeption in logfiles was:  

> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at megameklab.com.ui.view.MekChassisView.refreshStructure(MekChassisView.java:481)
	at megameklab.com.ui.view.MekChassisView.refresh(MekChassisView.java:401)
	at megameklab.com.ui.view.MekChassisView.setFromEntity(MekChassisView.java:311)
	at megameklab.com.ui.Mek.tabs.StructureTab.refresh(StructureTab.java:156)
	at megameklab.com.ui.Mek.MainUI.refreshAll(MainUI.java:214)
	at megameklab.com.ui.Mek.tabs.BuildTab.autoFillCrits(BuildTab.java:150)
	at megameklab.com.ui.Mek.tabs.BuildTab.actionPerformed(BuildTab.java:105)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)

> 

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/1380456/megameklablog.txt)
[megameklablog(mekhq0.43.4).txt](https://github.com/MegaMek/megameklab/files/1380418/megameklablog.mekhq0.43.4.txt)

[Spider SDR-96DF.zip](https://github.com/MegaMek/megameklab/files/1380429/Spider.SDR-96DF.zip)

**Comment by neoancient** [comment]
This was fixed in 55588a4.
